### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by tanxiaoke6** [liyuke65535/MMVRAC-reid#1]
Hello, your work is excellent. Congratulations on winning the competition. After reviewing your code, I have a few questions:

When training on the UAVHuman dataset, is it possible to not use the pre-trained weights you provided?
I would like to use another dataset for research, but the format of the other dataset is .npz. If I want to use your method, which files' code should I modify?

**Comment by liyuke65535** [comment]
Thank you!

- we use pre-trained weights for a better performance. You can just use the weights trained on Image-net. But it is not recommended to load non-trained random weights to train on ReID datasets, which may be much worse than pre-trained ones cuz the volume of finetune set is small.

- the code of ours doesn't include processing npz files. You can write a method to read npz files, then either transform them into jpg or png, either write a method directly process with pixel matrixes.

  - You should carefully check the data form inside npz files like the shape, the value range. If the data form is the same with reading from an original jpg/png, you can just conduct image transforms (like resize into 256*128) and feed the data into your model.

**Comment by tanxiaoke6** [comment]
OK, thank you for your reply.
